apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api
  namespace: transaction-api
spec:
  template:
    spec:
      containers:
        - name: transaction-api
          env:
            # X-Ray OTLP endpoint
            - name: OTLP_ENDPOINT
              value: "https://xray.sa-east-1.amazonaws.com"
            # X-Ray Java Agent via JAVA_TOOL_OPTIONS
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -javaagent:/tmp/opentelemetry-javaagent.jar
                -Dotel.service.name=transaction-api
                -Dotel.traces.exporter=otlp
                -Dotel.exporter.otlp.traces.endpoint=https://xray.sa-east-1.amazonaws.com
                -Dotel.exporter.otlp.traces.protocol=http/protobuf
                -Dotel.metrics.exporter=otlp
                -Dotel.exporter.otlp.metrics.endpoint=https://xray.sa-east-1.amazonaws.com
                -Dotel.exporter.otlp.metrics.protocol=http/protobuf
                -Dotel.resource.attributes=service.name=transaction-api,service.namespace=TransactionAPI