apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transaction-api

resources:
  - ../../base

patches:
  - path: serviceaccount-patch.yaml
  - path: deployment-patch.yaml

configMapGenerator:
  - name: transaction-api-config
    behavior: merge
    literals:
      - CLOUDWATCH_ENABLED=true
      - CLOUDWATCH_NAMESPACE=TransactionAPI
      - PROMETHEUS_ENABLED=false
      - AWS_SECRETS_ENABLED=true
      - OTLP_ENDPOINT=https://xray.sa-east-1.amazonaws.com
      - TRACING_SAMPLING_PROBABILITY=1.0
      - ACTUATOR_EXPOSURE=health,info,metrics