apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api
  namespace: transaction-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/transaction-api-eks-role