apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-api-config
  namespace: transaction-api
  labels:
    app.kubernetes.io/name: transaction-api
    app.kubernetes.io/part-of: transaction-system
data:
  SERVER_PORT: "8080"
  AWS_DEFAULT_REGION: "sa-east-1"
  SQS_POLL_INTERVAL: "5000"
  JWT_EXPIRATION: "86400"
  AWS_SECRETS_ENABLED: "true"
  PROMETHEUS_ENABLED: "false"
  CLOUDWATCH_ENABLED: "true"
  CLOUDWATCH_NAMESPACE: "TransactionAPI"
  TRACING_ENABLED: "true"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  ACTUATOR_EXPOSURE: "health,info,metrics"
  LOG_LEVEL: "INFO"
  LOG_LEVEL_MONGODB: "WARN"