apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api
  namespace: transaction-api
  labels:
    app.kubernetes.io/name: transaction-api
    app.kubernetes.io/part-of: transaction-system
  annotations:
    eks.amazonaws.com/role-arn: ""  # Será sobrescrito pelo overlay AWS