environment           = "dev"
aws_region            = "sa-east-1"
vpc_cidr              = "10.0.0.0/16"
availability_zones    = ["sa-east-1a", "sa-east-1b"]
container_cpu         = 512
container_memory      = 1024
desired_count         = 1
db_instance_class     = "db.r6g.large"
allowed_cidr_blocks   = ["0.0.0.0/0"]