environment           = "staging"
aws_region            = "sa-east-1"
vpc_cidr              = "10.1.0.0/16"
availability_zones    = ["sa-east-1a", "sa-east-1b"]
container_cpu         = 1024
container_memory      = 2048
desired_count         = 2
db_instance_class     = "db.r6g.large"
allowed_cidr_blocks   = ["10.0.0.0/8"]