apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transaction-api

resources:
  - ../../base

configMapGenerator:
  - name: transaction-api-config
    behavior: merge
    literals:
      - CLOUDWATCH_ENABLED=false
      - PROMETHEUS_ENABLED=true
      - AWS_SECRETS_ENABLED=false
      - OTLP_ENDPOINT=http://jaeger:4318
      - TRACING_SAMPLING_PROBABILITY=1.0
      - ACTUATOR_EXPOSURE=health,info,prometheus,metrics
      - LOG_LEVEL=DEBUG
      - LOG_LEVEL_MONGODB=DEBUG